// Todos los textos de la interfaz, en un solo lugar.
// La voz lee estas mismas frases: no hay símbolos.

export const TEXTOS = {
  titulo: "Cuentos Revueltos",
  leer: "Leer",
  seguirCuento: "Seguir el cuento",
  seguir: "Seguir",
  salir: "Salir",
  preguntaSalir: "¿Salir?",
  saltar: "Saltar",
  escuchar: "Escuchar",
  listo: "Listo",
  soltar: "Soltar",
  anterior: "Página anterior",
  enEspanol: "En español",
  como: "¿Cómo se juega?",
  reto: "Reto del día",
  otra: "Otra vez",
  oirCuento: "Oír el cuento",
  bloqueado: "Todavía no",
  cruce: "Elige un final.",
  noCuenta: "¡Este no cuenta, es para jugar!",
  noAqui: "Esta no va aquí",
  bien: "¡Así es!",
  era: "Era esta.",
  brillaTv: "¡Brilla! Pulsa OK en Listo.",
  brillaToca: "Toca Listo.",
  finCap: "Capítulo listo",
  retoOk: "¡Reto cumplido!",
  retoNo: "Sigue practicando",
  vozSi: "Voz: sí",
  vozNo: "Voz: no",
  vamos: "¡Vamos a leer!",
  palabraDia: "Palabra del día",
  paginaDia: "Página perdida",
  sinEstrellas: "Lee un capítulo para ganar estrellas",
  meta: "Meta",
  de: "de",
  capitulo: "Capítulo",
  domina: "¡Ya dominas este cuento!",
  mano: "En la mano",
};
